### ISSUE TITLE
Pet shop

### ISSUE THREAD

**Issue by Andyauk** [swkeep/keep-companion#1]
As a suggestion, you could use the free mlo for the pet shop. 

https://www.gta5-mods.com/maps/mlo-pet-shop

**Comment by swkeep** [comment]
Hi, it's just a matter of adding its coords inside qb-shops. 
I will add it as a comment inside the readme.md
ty

**Comment by Andyauk** [comment]
> Hi, it's just a matter of adding its coords inside qb-shops. I will add it as a comment inside the readme.md ty

No, keep up the great work, I'm going to check out your hunting script now. Looking forward to more

**Comment by swkeep** [comment]
❤️
