### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GhostLegionRP** [swkeep/keep-companion#13]
[script:keep-companio] SCRIPT ERROR: @keep-companion/server/functions.lua:94: attempt to index a string value (field 'info')

**Comment by swkeep** [comment]
Hi, my code has nothing in that line. can you check which function is in that line?

**Comment by GhostLegionRP** [comment]
its this 90-97

```
90 function updateInfoHelper(Player, slot, data)
91    if Player.PlayerData.items[slot] then
92        Player.PlayerData.items[slot].info[data.key] = data.content
93    end
94    -- print('how much: ', data.content, 'itemHash: ' .. Player.PlayerData.items[slot].info['hash'],
95    --     "whichPart: " .. data.key)
96    Player.Functions.SetInventory(Player.PlayerData.items, true)
97 end
```

I use your TEST Build

**Comment by swkeep** [comment]
I merged the test branch with the main branch. test it out it most likely fixes the issues.
