### ISSUE TITLE
flip car don't work

### ISSUE THREAD

**Issue by Andyauk** [swkeep/keep-companion#15]
i see in the c_util you have a clip car, but it dont work lots of errors.

<a href="https://ibb.co/wdqsVVt"><img src="https://i.ibb.co/VLGmRR6/fli.png" alt="fli" border="0"></a>

add this
local QBCore = exports['qb-core']:GetCoreObject()

change
CoreName.Functions.Progressbar("flipingcAr", "Fliping car", Config.Settings.carFlipingDuration * 1000,
to
QBCore.Functions.Progressbar("flipingcAr", "Fliping car", Config.Settings.carFlipingDuration * 1000,

**Comment by swkeep** [comment]
Hi, actually flip car should not be in this script but I don't have a better place to put this code there :)
