### ISSUE TITLE
Error coming up

### ISSUE THREAD

**Issue by AndreasFromDanmark** [swkeep/keep-companion#17]
I dont know 

![image](https://user-images.githubusercontent.com/35656492/169935589-c0ccc688-0c67-42f4-9dcd-1c25d02d1a43.png)

**Comment by swkeep** [comment]
Hi, I take a look at it. my question is what name are you giving to your pet?

**Comment by AndreasFromDanmark** [comment]
I tried to named it "test", just to see what the new update you uploaded could

**Comment by swkeep** [comment]
check out new commit should fix issue.

**Comment by AndreasFromDanmark** [comment]
@swkeep Alright will take a look ;)

**Comment by AndreasFromDanmark** [comment]
@swkeep When i use the pet collar

![image](https://user-images.githubusercontent.com/35656492/169940575-99bdebf7-e327-4dc3-b8b7-d67334956c65.png)

**Comment by swkeep** [comment]
yes i did not implement pet collar functions yet. later it should change ownership of pets.

**Comment by AndreasFromDanmark** [comment]
@swkeep Alright :)
