### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by GhostLegionRP** [swkeep/keep-companion#19]
Medikit are not removed by healing.
Collarpet not function.

**Comment by swkeep** [comment]
@GhostLegionRP first aid should only be removed when pets need to heal maybe they were not on low life!

**Comment by GhostLegionRP** [comment]
> @GhostLegionRP first aid should only be removed when pets need to heal maybe they were not on low life!

Pet had 50% atm

**Comment by swkeep** [comment]
after further testing, i found sometimes qbcore can't remove items from player inventory
