### ISSUE TITLE
pet shop seller & other changes

### ISSUE THREAD

**Issue by Andyauk** [swkeep/keep-companion#2]
this is the qb-shop update, also you are missing the pets images, to put in the inventory. 
when the pet levels up, you need to put a gap between name and level. as it says namelevel

when you type /renamepet there is two commands that come up /renamePet and /renamepet

in the qb-shop you have two keepcompanionretriever i guess one should be keepcompanionrottweiler
also in qb-shop you have Lion 3 times when there is only 2, so 9 not 10
as the lions don't show up, even on your preview you might want to pick something from
https://docs.fivem.net/docs/game-references/ped-models/#animals

maybe a kitty:)
PS just noticed you updated some stuff, mine was a older copy.

```
    ["petShop"] = {
        ["label"] = "Pet Shop",
        ["coords"] = vector4(-3225.63, 928.89, 13.9, 297.06),
        ["ped"] = 'S_M_M_StrVend_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "far fa-comment",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["petShop"],
        ["showblip"] = true,
        ["blipsprite"] = 267,
        ["colour"] = 5
    },
```

keep up the great work looking forward to updates.

**Comment by swkeep** [comment]
yea I used uppercase inside their names that caused the issue I will push a quick fix for it!

**Comment by Andyauk** [comment]
> yea I used uppercase inside their names that caused the issue I will push a quick fix for it!

Looking forward to checking out the updates, I would suggest changing the icon on the ped from 
        ["targetIcon"] = "fas fa-gun", to         ["targetIcon"] = "far fa-comment" or something, but that's upto you.

**Comment by Andyauk** [comment]
for the pet mlo I would suggest `vector4(563.76, 2753.27, 42.88, 186.12)`
