### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shadowTW** [swkeep/keep-companion#20]
![image](https://user-images.githubusercontent.com/64441627/170305754-f315fd3d-042c-4684-9f60-c5f479e15dd3.png)
![image](https://user-images.githubusercontent.com/64441627/170305801-ca058242-c678-4299-9c0c-67c17b2abb5d.png)

**Comment by swkeep** [comment]
i could not replicate this error whatsoever.
what's the item's name? and pls send me your config file if it's possible.
