### ISSUE TITLE
liter error

### ISSUE THREAD

**Issue by Andyauk** [swkeep/keep-companion#23]
```
[script:keep-companio] SCRIPT ERROR: @keep-companion/server/server.lua:266: attempt to compare number with nil
[script:keep-companio] SCRIPT ERROR: @keep-companion/server/server.lua:266: attempt to compare number with nil
```

```
    if type(item.info) == "table" then
        if item.info.liter > max_c then
            TriggerClientEvent('QBCore:Notify', source, 'could not do that already reached max capacity', 'error', 2500)
            return
        elseif item.info.liter == max_c then
            amount = max_c
```

**Comment by swkeep** [comment]
Hi, i have a question about the issue. before this error occurs did this notification "Washing new water bottle!" appear in your game?

**Comment by Andyauk** [comment]
> Hi, i have a question about the issue. before this error occurs did this notification "Washing new water bottle!" appear in your game?

yes i believe it did. i went to get a bottle. and i clicked don it i think.

**Comment by smouj013** [comment]
https://github.com/swkeep/keep-companion/issues/25
