### ISSUE TITLE
Problems ins de app.js

### ISSUE THREAD

**Issue by justBMR** [swkeep/keep-companion#26]
![image](https://user-images.githubusercontent.com/93486510/173249086-793b7377-860e-4449-9fe2-ca68ad148bc7.png)

Boa tarde,

Instalei todo o script como indicado no README.
Contudo, este erro surge no app.js e não entendo porque. Abaixo segue o código.

function FormatItemInfo(itemData, dom) {

    let element = $('.ply-iteminfo-container');
    let itemOffset = $(dom).offset();
    element.css('top', itemOffset.top - element.height());
    let leftOffset = itemOffset.left + 92;
    if (leftOffset + element.width() > $(window).width()) {
        leftOffset = $(window).width() - element.width() - 20;
    }
    element.css('left', leftOffset);

    if (itemData != null && itemData.info != "") {
        if (itemData.name == "id_card") {
            var gender = "Man";
            if (itemData.info.gender == 1) {
                gender = "Woman";
            }
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                '<p><strong>CSN: </strong><span>' + 
                itemData.info.citizenid + 
                '</span></p><p><strong>First Name: </strong><span>' + 
                itemData.info.firstname + 
                '</span></p><p><strong>Last Name: </strong><span>' + 
                itemData.info.lastname + 
                '</span></p><p><strong>Birth Date: </strong><span>' + 
                itemData.info.birthdate + 
                '</span></p><p><strong>Gender: </strong><span>' + 
                gender + 
                '</span></p><p><strong>Nationality: </strong><span>' + 
                itemData.info.nationality + 
                '</span></p>' + '</span></p><p><strong>Fingerprint: </strong><span>' + 
                itemData.info.fingerprint + '</span></p>'
            );
        } else if (itemData.name == "driver_license") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                "<p><strong>First Name: </strong><span>" +
                itemData.info.firstname +
                "</span></p><p><strong>Last Name: </strong><span>" +
                itemData.info.lastname +
                "</span></p><p><strong>Birth Date: </strong><span>" +
                itemData.info.birthdate +
                "</span></p><p><strong>Licenses: </strong><span>" +
                itemData.info.type +
                "</span></p>"
            );
        } else if (itemData.name == "weaponlicense") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                "<p><strong>First Name: </strong><span>" +
                itemData.info.firstname +
                "</span></p><p><strong>Last Name: </strong><span>" +
                itemData.info.lastname +
                "</span></p><p><strong>Birth Date: </strong><span>" +
                itemData.info.birthdate +
                "</span></p>"
            );
        } else if (itemData.name == "lawyerpass") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                "<p><strong>Pass-ID: </strong><span>" +
                itemData.info.id +
                "</span></p><p><strong>First Name: </strong><span>" +
                itemData.info.firstname +
                "</span></p><p><strong>Last Name: </strong><span>" +
                itemData.info.lastname +
                "</span></p><p><strong>CSN: </strong><span>" +
                itemData.info.citizenid +
                "</span></p>"
            );
            else if (
                itemData.name == "keepcompanionhusky" ||
                itemData.name == "keepcompanionrottweiler" ||
                itemData.name == "keepcompanionmtlion" ||
                itemData.name == "keepcompanionmtlion2" ||
                itemData.name == "keepcompanioncat" ||
                itemData.name == "keepcompanionpoodle" ||
                itemData.name == "keepcompanionpug" ||
                itemData.name == "keepcompanionretriever" ||
                itemData.name == "keepcompanionshepherd" ||
                itemData.name == "keepcompanionwesty"
            ) {
                let gender = itemData.info.gender;
                gender ? (gender = "male") : (gender = "female");
                $(".item-info-title").html("<p>" + itemData.info.name + "</p>");
                $(".item-info-description").html(
                    "<p><strong>Owner Phone: </strong><span>" +
                    itemData.info.owner.phone +
                    "</span></p><p><strong>Variation: </strong><span>" +
                    `${itemData.info.variation}` +
                    "</span></p><p><strong>Gender: </strong><span>" +
                    `${gender}` +
                    "</span></p><p><strong>Health: </strong><span>" +
                    itemData.info.health +
                    "</span></p><p><strong>Xp/Max: </strong><span>" +
                    `${itemData.info.XP} / ${maxExp(itemData.info.level)}` +
                    "</span></p><p><strong>Level: </strong><span>" +
                    itemData.info.level +
                    "</span></p><p><strong>Age: </strong><span>" +
                    callAge(itemData.info.age) +
                    "</span></p><p><strong>Food: </strong><span>" +
                    itemData.info.food +
                    "</span></p>" +
                    "</span></p><p><strong>Thirst: </strong><span>" +
                    itemData.info.thirst +
                    "</span></p>"
                );
            }
            else if (itemData.name == "petwaterbottleportable") {
                $(".item-info-title").html("<p>" + itemData.label + "</p>");
                $(".item-info-description").html("<p>capacity(L): " + itemData.info.liter + "</p>");
            }
        } else if (itemData.name == "harness") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                "<p>" + itemData.info.uses + " uses left.</p>"
            );
        } else if (itemData.type == "weapon") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            if (itemData.info.ammo == undefined) {
                itemData.info.ammo = 0;
            } else {
                itemData.info.ammo != null ? itemData.info.ammo : 0;
            }
            if (itemData.info.attachments != null) {
                var attachmentString = "";
                $.each(itemData.info.attachments, function(i, attachment) {
                    if (i == itemData.info.attachments.length - 1) {
                        attachmentString += attachment.label;
                    } else {
                        attachmentString += attachment.label + ", ";
                    }
                });
                $(".item-info-description").html(
                    "<p><strong>Serial: </strong><span>" +
                    itemData.info.serie +
                    "</span></p><p><strong>Ammo: </strong><span>" +
                    itemData.info.ammo +
                    "</span></p><p><strong>Attachments: </strong><span>" +
                    attachmentString +
                    "</span></p>"
                );
            } else {
                $(".item-info-description").html(
                    "<p><strong>Serial: </strong><span>" +
                    itemData.info.serie +
                    "</span></p><p><strong>Ammo: </strong><span>" +
                    itemData.info.ammo +
                    "</span></p><p>" +
                    itemData.description +
                    "</p>"
                );
            }
        } else if (itemData.name == "filled_evidence_bag") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            if (itemData.info.type == "casing") {
                $(".item-info-description").html(
                    "<p><strong>Evidence material: </strong><span>" +
                    itemData.info.label +
                    "</span></p><p><strong>Type number: </strong><span>" +
                    itemData.info.ammotype +
                    "</span></p><p><strong>Caliber: </strong><span>" +
                    itemData.info.ammolabel +
                    "</span></p><p><strong>Serial: </strong><span>" +
                    itemData.info.serie +
                    "</span></p><p><strong>Crime scene: </strong><span>" +
                    itemData.info.street +
                    "</span></p><br /><p>" +
                    itemData.description +
                    "</p>"
                );                
            } else if (itemData.info.type == "blood") {
                $(".item-info-description").html(
                    "<p><strong>Evidence material: </strong><span>" +
                    itemData.info.label +
                    "</span></p><p><strong>Blood type: </strong><span>" +
                    itemData.info.bloodtype +
                    "</span></p><p><strong>DNA Code: </strong><span>" +
                    itemData.info.dnalabel +
                    "</span></p><p><strong>Crime scene: </strong><span>" +
                    itemData.info.street +
                    "</span></p><br /><p>" +
                    itemData.description +
                    "</p>"
                );
            } else if (itemData.info.type == "fingerprint") {
                $(".item-info-description").html(
                    "<p><strong>Evidence material: </strong><span>" +
                    itemData.info.label +
                    "</span></p><p><strong>Fingerprint: </strong><span>" +
                    itemData.info.fingerprint +
                    "</span></p><p><strong>Crime Scene: </strong><span>" +
                    itemData.info.street +
                    "</span></p><br /><p>" +
                    itemData.description +
                    "</p>"
                );
            } else if (itemData.info.type == "dna") {
                $(".item-info-description").html(
                    "<p><strong>Evidence material: </strong><span>" +
                    itemData.info.label +
                    "</span></p><p><strong>DNA Code: </strong><span>" +
                    itemData.info.dnalabel +
                    "</span></p><br /><p>" +
                    itemData.description +
                    "</p>"
                );
            }
        } else if (
            itemData.info.costs != undefined &&
            itemData.info.costs != null
        ) {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html("<p>" + itemData.info.costs + "</p>");
        } else if (itemData.name == "stickynote") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html("<p>" + itemData.info.label + "</p>");
        } else if (itemData.name == "moneybag") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                "<p><strong>Amount of cash: </strong><span>$" +
                itemData.info.cash +
                "</span></p>"
            );
        } else if (itemData.name == "markedbills") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html(
                "<p><strong>Worth: </strong><span>$" +
                itemData.info.worth +
                "</span></p>"
            );
        } else if (itemData.name == "visa" || itemData.name == "mastercard") {
            $(".item-info-title").html('<p>'+itemData.label+'</p>')
            var str = ""+ itemData.info.cardNumber + "";
            var res = str.slice(12);
            var cardNumber = "************" + res;
            $(".item-info-description").html('<p><strong>Card Holder: </strong><span>' + itemData.info.name + '</span></p><p><strong>Citizen ID: </strong><span>' + itemData.info.citizenid + '</span></p><p><strong>Card Number: </strong><span>' + cardNumber + '</span></p>');
        } else if (itemData.name == "labkey") {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html("<p>Lab: " + itemData.info.lab + "</p>");
        } else {
            $(".item-info-title").html("<p>" + itemData.label + "</p>");
            $(".item-info-description").html("<p>" + itemData.description + "</p>");
        }
    } else {
        $(".item-info-title").html("<p>" + itemData.label + "</p>");
        $(".item-info-description").html("<p>" + itemData.description + "</p>");
    };
    
}

**Comment by swkeep** [comment]
Hi, I translated your message with google translate, and as far as I can see you are missing { in this line. 
![scac](https://user-images.githubusercontent.com/49286776/173249942-8ff80ff2-b565-4225-876c-c81cf5ff2ba7.PNG)

**Comment by justBMR** [comment]
Thanks for your reply

I've try this
![image](https://user-images.githubusercontent.com/93486510/173252552-0ce2d20c-a87d-4a2e-9b63-8bacc9bd63ae.png)
Return me a error

I try this
![image](https://user-images.githubusercontent.com/93486510/173252574-b5af8035-53b9-4c50-8518-412620ce8fe4.png)
The error pass to this place
![image](https://user-images.githubusercontent.com/93486510/173252606-ad29cd88-103c-4e75-9ce9-1e103092a20a.png)
![image](https://user-images.githubusercontent.com/93486510/173252611-f2c536bc-c304-48b9-9ed4-ec26ff158969.png)


It real strange this situation

**Comment by swkeep** [comment]
please send me the whole app.js i need to check something!

**Comment by LDPNZ** [comment]
Hey guys I think this was the issue I had and fixed it by making the first else if statement just an if statement i.e.

if (
     itemData.name == "keepcompanionhusky" ||
     itemData.name == "keepcompanionrottweiler" ||
and so on 

swkeep sorry I meant to let you know that fixed my issue after I raised it with you

**Comment by swkeep** [comment]
@LDPNZ np. Thanks for the solution.
I hope it helps @justBMR

**Comment by justBMR** [comment]
I have already changed the code as mentioned above.
Apparently it no longer generates errors in Visual studio code, but I won't be able to test everything properly until tonight when I leave work.
Then I leave feedback.

Thanks for the help, you guys are the greatest :D

**Comment by justBMR** [comment]
Tanks for the help guys, the soluction works perfect.

You guys are the greatest ❤️

**Comment by subhampro** [comment]
> 

can you share your APP.js
