### ISSUE TITLE
Rottweiler don't show

### ISSUE THREAD

**Issue by Andyauk** [swkeep/keep-companion#3]
Rottweiler don't warm up or show

**Comment by Andyauk** [comment]
<a href="https://ibb.co/FbKt7PH"><img src="https://i.ibb.co/sv2r3BW/petting.png" alt="petting" border="0"></a>

but i think your update might have sorted it. going to check it out now.

**Comment by swkeep** [comment]
yes, I did change the animation function to skip some models but I need to set animations manually It might take some time.

**Comment by Andyauk** [comment]
> yes, I did change the animation function to skip some models but I need to set animations manually It might take some time.

seems to do it on tricks too. not tested all

**Comment by Andyauk** [comment]
westy, cat, pug, poodle
