### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Lancmo** [swkeep/keep-companion#33]
When I finished setting up everything by following the steps listed in the github READ-ME, I restarted my server and tested it out and it did not work. When sending a command of /addpet it then sends a error in the console.

**Comment by Lancmo** [comment]
It does work if I go to the pet shop and buy one but its not showing the food/water/etc when hovering over a owned pet.

**Comment by swkeep** [comment]
you need to do app.js changes to be able to see information about pets

**Comment by Lancmo** [comment]
I did it just seems I did it wrong but I am not sure what I did wrong.
