### ISSUE TITLE
Bug or should be?

### ISSUE THREAD

**Issue by Leslija** [swkeep/keep-companion#37]
So, script works fine, thanks, but..

Doing nothing, the animal levels seem to update by one every minute. Is that how it should be?
I looked at the code and didn't see any update timer other than the mathematical formulas.

**Comment by swkeep** [comment]
yea this is how I intended to work.
the reason is checking pet coords every 1-2 sec was too expensive on some servers to run especially when they wanted to have more than 1 pet per player and on top of that I didn't want to add exp calculation client-side so I made like this.

**Comment by Leslija** [comment]
Thanks for the reply!
And again thanks for the great script!
