### ISSUE TITLE
important steps for K9 error

### ISSUE THREAD

**Issue by AndreasFromDanmark** [swkeep/keep-companion#38]
![Skærmbillede 2022-09-14 001029](https://user-images.githubusercontent.com/35656492/190019073-b8d6ae78-df2e-495f-a230-c692b0b49767.png)
![Skærmbillede 2022-09-14 001011](https://user-images.githubusercontent.com/35656492/190019077-2f209f23-61cf-45d1-ae67-0e10f57d8d3b.png)

error is coming after i added

exports('getTruck', function(id)
	return Trunks[id]
)

exports('getGloveboxes', function(id)
	return Gloveboxes[id]
)

**Comment by swkeep** [comment]
Hey, are you using the latest qbcore version? this might be because of that.

**Comment by AndreasFromDanmark** [comment]
@swkeep Yes its one of the most recent version

**Comment by swkeep** [comment]
@AndreasFromDanmark so I tested it with the new qbcore script works fine it's a miss type on your end.
```lua
exports('getTruck', function(id)
return Trunks[id]
)

exports('getGloveboxes', function(id)
return Gloveboxes[id]
)
```
This is wrong you're just missing `end` before ) at end of functions.

```lua
exports('getTruck', function(id)
	return Trunks[id]
end)

exports('getGloveboxes', function(id)
	return Gloveboxes[id]
end)
```

**Comment by AndreasFromDanmark** [comment]
@swkeep Thanks :) it worked
