### ISSUE TITLE
Reading phone issue

### ISSUE THREAD

**Issue by OfficialRDB** [swkeep/keep-companion#46]
![Capture](https://user-images.githubusercontent.com/50579206/203226172-4f1bc1fc-eab9-4ba0-99e0-c179910c608d.PNG)

When I hover over the pet in my inventory to see the information, it returns this error.

**Comment by swkeep** [comment]
This is not related to my script. it happens when there is a mistake in the inventory modification step.
check this video this is how you should do it.
https://drive.google.com/file/d/1cpIXz7Q6_lSbccTtsb_tgjSdp7bzUZ7L/view
gl

**Comment by OfficialRDB** [comment]
But it shows that when you did not setup the dog, and you hover over it. Everything return undefined. If you did setup the name ect...., everything works and shows fine.

**Comment by PEROXCYDE** [comment]
> if (itemData.info.name

where you put this?

**Comment by PEROXCYDE** [comment]
![image](https://github.com/swkeep/keep-companion/assets/108100343/98a0934a-f00c-455a-9e3e-2267b9fec788)
