### ISSUE TITLE
Menu and Shop

### ISSUE THREAD

**Issue by GhostLegionRP** [swkeep/keep-companion#5]
Shop hasn't all Pets (Lions not there)

When I press "O" first time it will show the cursor then i must press and hold again and the menu will show... maybe it possible to use the normal QB-radialmenu to fix this error

Sorry for my bad english. =)

![pets](https://user-images.githubusercontent.com/100316482/164323378-736bc26a-28ae-4e20-95c8-9332d487b493.PNG)
.

**Comment by swkeep** [comment]
Hi, i noticed that i didn't update the readme.md 
to fix missing pets you should use lower case lion in both items inside qb-core/shared/items.lua for example

keepcompanionmtLion ==> keepcompanionmtlion

and about the menu, actually, it works how i intended it to work but it's kinda broken :).
I will rework it with qb-menu next week
