### ISSUE TITLE
commands posting 3 times.

### ISSUE THREAD

**Issue by Andyauk** [swkeep/keep-companion#6]
commands are posting 3 times.

**Comment by swkeep** [comment]
Hi, i need more information about that! screenshot or a way to reproduce it

**Comment by Andyauk** [comment]
> Hi, i need more information about that! screenshot or a way to reproduce it

ill close this for now, as it might have been i needed a reboot. as it was went i would do a trick or follow. the notify came up 3 times. but its fine after a reboot. ill let you know.
